SELECT
    ENT_DATE,PHONE,CONCAT_WS(
        '-',
        SUBSTRING(PHONE,1,3),
        SUBSTRING(PHONE,4,4),
        SUBSTRING(PHONE,8,4)
        ) AS 'PHONE'

FROM
    employee
WHERE
    SUBSTRING(PHONE,1,3) = '010';
#     phone LIKE '010';

SELECT
    EMP_NAME AS '직원명',
    HIRE_DATE,
    CONCAT(YEAR(HIRE_DATE)'년',MONTH(HIRE_DATE)'월',DAY(HIRE_DATE)'일'),
    FORMAT(SALARY,0) AS '급여'
FROM
    employee
WHERE
    HIRE_DATE <= SUBDATE(CURDATE(), INTERVAL 20 YEAR)
ORDER BY
    HIRE_DATE ASC,SALARY DESC;
-- 1990-02-06
SELECT '2010-02-06' <= SUBDATE(CURDATE(), INTERVAL 20 YEAR);
